# ==============================================================================
# INL Portfolio Project: MHTGR Hexagonal Monolith
# Coupled Steady-State Thermal-Mechanical Analysis
# ==============================================================================

[Mesh]
  # Load the Exodus mesh generated by Coreform Cubit
  [fmg]
    type = FileMeshGenerator
    file = '../meshes/monolith.e'
  []
  
  # Scale mesh from cm/mm to meters to match standard SI unit definitions
  [scale_to_meters]
    type = TransformGenerator
    input = fmg
    transform = SCALE
    vector_value = '0.01 0.01 0.01'
  []

  # --- Isostatic 3-2-1 Constraint Nodeset Generation ---
  # These blocks locate specific points on the geometry to anchor the model
  # preventing rigid body motion without artificially constraining thermal expansion.
  [pt1]
    type = ExtraNodesetGenerator
    input = scale_to_meters
    new_boundary = 'pin_pt1'
    coord = '0.2078 0.0 0.0'
    tolerance = 0.05
  []
  
  [pt2]
    type = ExtraNodesetGenerator
    input = pt1
    new_boundary = 'pin_pt2'
    coord = '-0.2078 0.0 0.0'
    tolerance = 0.05
  []
  
  [pt3]
    type = ExtraNodesetGenerator
    input = pt2
    new_boundary = 'pin_pt3'
    coord = '0.0 0.0 0.18'
    tolerance = 0.05
  []
[]

[Variables]
  # Primary thermal variable solved via heat conduction
  [temperature]
    order = FIRST
    family = LAGRANGE
    initial_condition = 300
  []
[]

[GlobalParams]
  # Globally define displacement variables for the SolidMechanics physics block
  displacements = 'displacement_x displacement_y displacement_z'
[]

[Physics]
  # Automatically generates the necessary Tensor Mechanics kernels
  [SolidMechanics]
    [QuasiStatic]
      [all]
        strain = SMALL
        add_variables = true
        eigenstrain_names = thermal_expansion
        generate_output = 'stress_xx stress_yy stress_zz vonmises_stress hydrostatic_stress'
        temperature = temperature
      []
    []
  []
[]

[Kernels]
  # Heat equation terms: -k * Laplacian(T) = Q
  [heat_conduction]
    type = HeatConduction
    variable = temperature
  []
  [heat_source]
    type = BodyForce
    variable = temperature
    value = 5e6
  []
[]

[BCs]
  # Convective heat transfer cooling applied to the internal channel walls
  [convective_cooling]
    type = ConvectiveHeatFluxBC
    variable = temperature
    boundary = 'channel_walls'
    T_infinity = 600
    heat_transfer_coefficient = 2000
  []

  # --- 3-2-1 Kinematic Constraints ---
  # Point 1: Fixed in X, Y, Z (Pin)
  [pt1_x]
    type = DirichletBC
    variable = displacement_x
    boundary = pin_pt1
    value = 0
  []
  [pt1_y]
    type = DirichletBC
    variable = displacement_y
    boundary = pin_pt1
    value = 0
  []
  [pt1_z]
    type = DirichletBC
    variable = displacement_z
    boundary = pin_pt1
    value = 0
  []

  # Point 2: Fixed in Y, Z (Roller constraining rotation about Z and Y)
  [pt2_y]
    type = DirichletBC
    variable = displacement_y
    boundary = pin_pt2
    value = 0
  []
  [pt2_z]
    type = DirichletBC
    variable = displacement_z
    boundary = pin_pt2
    value = 0
  []

  # Point 3: Fixed in Y (Roller constraining rotation about X)
  [pt3_y]
    type = DirichletBC
    variable = displacement_y
    boundary = pin_pt3
    value = 0
  []
[]

[Materials]
  # --- Thermal Properties (IG-110 Graphite) ---
  [graphite_conductivity]
    type = ParsedMaterial
    block = 'monolith_graphite'
    property_name = 'thermal_conductivity'
    coupled_variables = 'temperature'
    expression = '9000 / temperature'
  []

  [graphite_heat_capacity]
    type = GenericConstantMaterial
    block = 'monolith_graphite'
    prop_names = 'specific_heat'
    prop_values = '700'
  []

  # --- Mechanical Properties (IG-110 Graphite) ---
  [elasticity_tensor]
    type = ComputeIsotropicElasticityTensor
    block = 'monolith_graphite'
    youngs_modulus = 10e9
    poissons_ratio = 0.14
  []
  [linear_stress]
    type = ComputeLinearElasticStress
    block = 'monolith_graphite'
  []

  [thermal_expansion]
    type = ComputeThermalExpansionEigenstrain
    block = 'monolith_graphite'
    temperature = temperature
    stress_free_temperature = 300
    thermal_expansion_coeff = 4.5e-6
    eigenstrain_name = thermal_expansion
  []
[]

[Executioner]
  type = Steady
  solve_type = 'PJFNK'
  petsc_options_iname = '-pc_type -pc_hypre_type'
  petsc_options_value = 'hypre boomeramg'
[]

[Postprocessors]
  # Evaluates and reports peak values to the terminal and CSV during the solve
  [max_T]
    type = NodalExtremeValue
    variable = temperature
  []
  
  # Finds the maximum von Mises stress across all elements
  [max_vonmises]
    type = ElementExtremeValue
    variable = vonmises_stress
  []
[]

[Outputs]
  exodus = true
  csv = true
  print_linear_residuals = false
[]